version: 2.1

# Pipeline workflow parameters
parameters:
  remote_trigger:
    type: enum
    enum: ['default', 'update-packages']
    default: 'default'

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: echo "build"
  pr:
    docker:
      - image: alpine
    steps:
      - run: echo "pr"

  update-packages:
    docker:
      - image: alpine
    steps:
      - run: ~/project/merp.sh

  automerge:
    docker:
      - image: alpine
    steps:
      - run: echo "pr"

# Workflows
workflows:
  update-packages:
    when:
      equal: [<< pipeline.parameters.remote_trigger >>, 'update-packages']
    jobs:
      - update-packages:
          filters:
            branches:
              only: master

  pull-request:
    jobs:
      - pr:
          filters:
            branches:
              ignore: master
      - automerge:
          filters:
            branches:
              only:
                - /^rbibot\/rbilabs\/.*/
          requires:
            - pr

  master:
    when:
      equal: [<< pipeline.parameters.remote_trigger >>, 'default']
    jobs:
      - build:
          filters:
            branches:
              only: master
